config/routes.rb
Rails.application.routes.draw do
    
  root 'restaurants#index'
  ActiveAdmin.routes(self)
  devise_for :users
  resources :restaurants
  resources :dishes
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.is_admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant

  has_one_attached :picture
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :dishes

	has_one_attached :image
	validates :image, file_content_type: 
				{ allow: ['image/jpeg', 'image/gif', 'image/png'] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :name, presence:true, length: { maximum: 50 }
  validates :phone, presence:true, length: { maximum: 20 }
  validates :address, presence:true, length: { maximum: 150 }

  before_save { self.name.capitalize! }
  before_save { self.email.downcase! }

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  
	def access_denied(exception)
		flash[:danger] = exception.message
		redirect_to root_url
	end

	private

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :address])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :address])
	end
end

app/controllers/dish_controller.rb
class DishController < ApplicationController
  def show
  	@dish = Dish.find(params[:id])
  end

  private

  def dishes_params
  	params.require(:dish).permit(:title, :description, :price, :picture)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
  	@restaurants = Restaurant.all 
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  private

  def resrtaurants_params
  	params.require(:restaurant).permit(:name, :description)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dish_helper.rb
module DishHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dish/show.html.erb
<h1>Dish</h1>

<p>	
	<%= image_tag @dish.picture %>
</p>

<p>
	<strong>Name:</strong>
	<%= @dish.title %>
</p>

<p>
	<strong>Description:</strong>
	<%= @dish.description %>
</p>

<p>
	<strong>Price:</strong>
	<%= @dish.price %>
</p>

<%= link_to 'Back', restaurants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FoodOuder</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/application/navbar' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<div class="container">
  		<div class="row">
    		<div class="col-sm">
				<%= yield %>
    		</div>
  		</div>
	</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
	<div class="container">
		<button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			&#x2630;
		</button>

		<%= link_to 'User', root_path, class: 'navbar-brand' %>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="nav-item"><a href="#" class="nav-link">About</a>
				</li>
				<li class="nav-item"><a href="#" class="nav-link">Contacts</a>
				</li>
			</ul>
			<div class="navbar-nav ml-auto">
				<div class="navbar-nav ml-auto">
					<% if user_signed_in? %>
					<div class="nav-item">
						<span class="navbar-text">
							Hello, &nbsp;
							<span>
							</div>                  
							<div class="dropdown show">
								<%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
								<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
									<%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
									<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
								</div>
								
								<% else %>
								<div class="nav-item">
									<%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
								</div>
								
								<div class="nav-item">
									<%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
								</div>
								<div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</nav>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="card" style="width: 20rem;">
	<% @restaurants.each do |restaurant| %>
	<%= link_to(image_tag(restaurant.image, size: 400, class:"img-fluid"), restaurant) if restaurant.image.attached? %>
		<div class="card-body">    
			<p class="card-text"><strong><%= restaurant.name %></strong></p>
			<p class="card-text"><strong><%= restaurant.description %></strong></p>	
		</div>
	<% end %>		
</div>

app/views/restaurants/show.html.erb
<%= link_to 'Back', restaurants_path %>	

<h1>Restaurant dishes</h1>

<div class="card" style="width: 18rem;">
	<%= image_tag @restaurant.image %>
	<div class="card-body">
		<h5 class="card-title">Saebiz</h5>
		<p class="card-text"><strong>Name:</strong>
		<%= @restaurant.name %></p>
		<p class="card-text"><strong>Description:</strong>
		<%= @restaurant.description %></p>  
	</div>
</div>
</br>
<% @restaurant.dishes.each do |dish| %>
<div class="card" style="width: 16rem;">
	<%= image_tag(dish.picture, size: 300, class:"img-fluid") if @restaurant.image.attached? %>  
	<div class="card-body">		
		<p class="card-text">Title: <%= dish.title %></p>
		<p class="card-text">Description: <%= dish.description %></p>  
		<p class="card-text">Price: <%= dish.price %></p> 				
	</div>
</div>
<% end %>